### ISSUE TITLE
[JENKINS-5008] email-ext plugin doesn't work with hudson 1.336

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/email-ext-plugin#679]
<p>The current email-ext version doesn't work with hudson build 1.336 . No configuration is possible</p>

<p>This is the stacktrace:</p>

<pre>
Dec 7, 2009 10:06:14 AM hudson.model.Hudson$4 onTaskFailed
SEVERE: Failed Loading plugin email-ext
hudson.util.IOException2: Failed to initialize
	at hudson.ClassicPluginStrategy.load(ClassicPluginStrategy.java:278)
	at hudson.PluginManager$1$3$2$1.run(PluginManager.java:202)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:146)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:259)
	at hudson.model.Hudson$3.runTask(Hudson.java:642)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:187)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:619)
Caused by: java.lang.NoClassDefFoundError: hudson/plugins/analysis/core/HealthAwarePublisher
</pre>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=fsimmend">fsimmend</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-5008" target="_blank">email-ext plugin doesn't work with hudson 1.336</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=fsimmend">fsimmend</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>component(s)</b>: email-ext-plugin
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2009-12-07T01:28:04+00:00
<li><b>votes</b>: 0
<li><b>watchers</b>: 1
<li><b>imported</b>: 20251211-141027
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>The current email-ext version doesn't work with hudson build 1.336 . No configuration is possible</p>

<p>This is the stacktrace:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">Dec 7, 2009 10:06:14 AM hudson.model.Hudson$4 onTaskFailed
SEVERE: Failed Loading plugin email-ext
hudson.util.IOException2: Failed to initialize
	at hudson.ClassicPluginStrategy.load(ClassicPluginStrategy.java:278)
	at hudson.PluginManager$1$3$2$1.run(PluginManager.java:202)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:146)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:259)
	at hudson.model.Hudson$3.runTask(Hudson.java:642)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:187)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:619)
Caused by: java.lang.NoClassDefFoundError: hudson/plugins/analysis/core/HealthAwarePublisher
</pre>
</div></div></pre>
</details>
</details>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>mdonohue:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-5008?focusedId=133827&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-133827">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Could you expand on what "No configuration is possible" means?  Or include a screenshot.</p>
</pre>
</details>

</ul>
</details>

<p>Could you expand on what "No configuration is possible" means?  Or include a screenshot.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>fsimmend:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-5008?focusedId=133892&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-133892">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>install analysis-core and everything works fine
real issues are  <a href="https://issues.jenkins.io/browse/JENKINS-5010" title="After upgrading a number of static analysis plugins 11 plugins were skipped to load and unlisted in the installed list" class="issue-link" data-issue-key="JENKINS-5010"><del>JENKINS-5010</del></a> <a href="https://issues.jenkins.io/browse/JENKINS-4983" title="Plugin dependencies ignored =&gt; various severe errors after restart" class="issue-link" data-issue-key="JENKINS-4983"><del>JENKINS-4983</del></a></p>
</pre>
</details>

</ul>
</details>

<p>install analysis-core and everything works fine<br/>
real issues are  <a href="https://issue-redirect.jenkins.io/issue/5010" title="After upgrading a number of static analysis plugins 11 plugins were skipped to load and unlisted in the installed list" class="issue-link" data-issue-key="<a class="jira-plain-text-key" href="https://issue-redirect.jenkins.io/issue/5010">JENKINS-5010</a>"><del>JENKINS-5010</del></a> <a href="https://issue-redirect.jenkins.io/issue/4983" title="Plugin dependencies ignored => various severe errors after restart" class="issue-link" data-issue-key="<a class="jira-plain-text-key" href="https://issue-redirect.jenkins.io/issue/4983">JENKINS-4983</a>"><del>JENKINS-4983</del></a></p>

**Comment by jenkins-infra-bot** [comment]
<i>[Original `duplicates` from Jira: <a class="jira-relationship" href="https://issue-redirect.jenkins.io/issue/4983">JENKINS-4983</a>]</i>
