### ISSUE TITLE
[JENKINS-20355] email-ext emails no longer include JUnit results

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/email-ext-plugin#976]
<p>After upgrading from 1.503 to LTS 1.509.4 and updating plugins to the latest released versions that work with LTS, I stopped getting JUnit test results in my build e-mails.  I use a custom jelly script based on the html.jelly template (the JUnit section of my template is identical to html.jelly).</p>

<p>In my jenkins.log I see:<br/>
WARNING: Caught exception evaluating: it.JUnitTestResult. Reason: java.lang.reflect.InvocationTargetException<br/>
...<br/>
Caused by: java.lang.NoClassDefFoundError: hudson/maven/reporters/SurefireAggregatedReport<br/>
at hudson.plugins.emailext.plugins.content.ScriptContentBuildWrapper.getJUnitTestResult(ScriptContentBuildWrapper.java:78)<br/>
...</p>

<p>This seems like it might be related to <a href="https://issues.jenkins-ci.org/browse/JENKINS-16990" class="external-link" target="_blank" rel="nofollow noopener">https://issues.jenkins-ci.org/browse/JENKINS-16990</a>, but I'm not sure how the fix for that issue applies in my situation.</p>

---
<details><summary><i>Originally reported by <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/randycoulman.jpg" title="randycoulman's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=randycoulman">randycoulman</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-20355" target="_blank">email-ext emails no longer include JUnit results</a></i></summary>
<i><ul>
<li><b>assignee</b>: <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/slide_o_mix.png" title="slide_o_mix's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=slide_o_mix">slide_o_mix</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>component(s)</b>: email-ext-plugin
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2013-10-30T23:45:48+00:00
<li><b>votes</b>: 0
<li><b>watchers</b>: 3
<li><b>imported</b>: 20251211-172001
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>After upgrading from 1.503 to LTS 1.509.4 and updating plugins to the latest released versions that work with LTS, I stopped getting JUnit test results in my build e-mails.  I use a custom jelly script based on the html.jelly template (the JUnit section of my template is identical to html.jelly).</p>

<p>In my jenkins.log I see:
WARNING: Caught exception evaluating: it.JUnitTestResult. Reason: java.lang.reflect.InvocationTargetException
...
Caused by: java.lang.NoClassDefFoundError: hudson/maven/reporters/SurefireAggregatedReport
        at hudson.plugins.emailext.plugins.content.ScriptContentBuildWrapper.getJUnitTestResult(ScriptContentBuildWrapper.java:78)
...</p>

<p>This seems like it might be related to <a href="https://issues.jenkins-ci.org/browse/JENKINS-16990" class="external-link" target="_blank" rel="nofollow noopener">https://issues.jenkins-ci.org/browse/JENKINS-16990</a>, but I'm not sure how the fix for that issue applies in my situation.</p></pre>
</details>
</details>
<ul><li><i>environment</i>: <code>Debian Linux squeeze i386; Jenkins LTS 1.509.4</code></li></ul>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/randycoulman.jpg" title="randycoulman's avatar" /> randycoulman:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-20355?focusedId=188796&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-188796">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>This issue seems similar.</p>
</pre>
</details>

</ul>
</details>

<p>This issue seems similar.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/slide_o_mix.png" title="slide_o_mix's avatar" /> slide_o_mix:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-20355?focusedId=188797&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-188797">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Can you post your job's config.xml and the email template?</p>
</pre>
</details>

</ul>
</details>

<p>Can you post your job's config.xml and the email template?</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/slide_o_mix.png" title="slide_o_mix's avatar" /> slide_o_mix:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-20355?focusedId=188798&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-188798">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Also, can you make sure that the maven plugin is installed and activated?</p>
</pre>
</details>

</ul>
</details>

<p>Also, can you make sure that the maven plugin is installed and activated?</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/randycoulman.jpg" title="randycoulman's avatar" /> randycoulman:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-20355?focusedId=188800&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-188800">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>I had the Maven Integration plugin disabled; re-enabling it fixed the problem.  Thanks for the help!</p>
</pre>
</details>

</ul>
</details>

<p>I had the Maven Integration plugin disabled; re-enabling it fixed the problem.  Thanks for the help!</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/randycoulman.jpg" title="randycoulman's avatar" /> randycoulman:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-20355?focusedId=188801&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-188801">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>This was a configuration problem: Maven Integration plugin needs to be enabled.</p>
</pre>
</details>

</ul>
</details>

<p>This was a configuration problem: Maven Integration plugin needs to be enabled.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/s0undt3ch.png" title="s0undt3ch's avatar" /> s0undt3ch:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-20355?focusedId=217361&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-217361">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>I seem to be getting this using latest jenkins and latest email-ext plugin. And I'm also not getting the violations.</p>

<p>Jenkins ver. 1.592
email-ext 2.39</p>
</pre>
</details>

</ul>
</details>

<p>I seem to be getting this using latest jenkins and latest email-ext plugin. And I'm also not getting the violations.</p>

<p>Jenkins ver. 1.592<br/>
email-ext 2.39</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/slide_o_mix.png" title="slide_o_mix's avatar" /> slide_o_mix:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-20355?focusedId=217370&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-217370">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Can you give more details? You are getting the noclassdefexception? Do you have the maven project plugin installed and enabled?</p>
</pre>
</details>

</ul>
</details>

<p>Can you give more details? You are getting the noclassdefexception? Do you have the maven project plugin installed and enabled?</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/s0undt3ch.png" title="s0undt3ch's avatar" /> s0undt3ch:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-20355?focusedId=217383&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-217383">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>I'm not getting the traceback, so I should probably open a new issue..</p>

<p>I have Maven Integration plugin 2.8 installed and enabled..</p>

<p>Also, this is not a maven project, it's a freestyle project(if that makes a difference)</p>
</pre>
</details>

</ul>
</details>

<p>I'm not getting the traceback, so I should probably open a new issue..</p>

<p>I have Maven Integration plugin 2.8 installed and enabled..</p>

<p>Also, this is not a maven project, it's a freestyle project(if that makes a difference)</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/s0undt3ch.png" title="s0undt3ch's avatar" /> s0undt3ch:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-20355?focusedId=217384&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-217384">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>I'm also not getting the warnings reports in the email either...</p>
</pre>
</details>

</ul>
</details>

<p>I'm also not getting the warnings reports in the email either...</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/s0undt3ch.png" title="s0undt3ch's avatar" /> s0undt3ch:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-20355?focusedId=217385&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-217385">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>My email template <a href="https://gist.github.com/s0undt3ch/8d220faaa3b0614ee3b0" class="external-link" target="_blank" rel="nofollow noopener">https://gist.github.com/s0undt3ch/8d220faaa3b0614ee3b0</a></p>
</pre>
</details>

</ul>
</details>

<p>My email template <a href="https://gist.github.com/s0undt3ch/8d220faaa3b0614ee3b0" class="external-link" target="_blank" rel="nofollow noopener">https://gist.github.com/s0undt3ch/8d220faaa3b0614ee3b0</a></p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/s0undt3ch.png" title="s0undt3ch's avatar" /> s0undt3ch:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-20355?focusedId=217386&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-217386">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Actually, after your comment I did enable the maven integration plugin, previously disabled. Tried a test run with no success.
Today I tried again, and it's working again. Sorry for the confusion.</p>

<p>I'm still unable to get the violations report though... (if only I know jenkins java classes better and jelly for that matter)...</p>
</pre>
</details>

</ul>
</details>

<p>Actually, after your comment I did enable the maven integration plugin, previously disabled. Tried a test run with no success.<br/>
Today I tried again, and it's working again. Sorry for the confusion.</p>

<p>I'm still unable to get the violations report though... (if only I know jenkins java classes better and jelly for that matter)...</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/slide_o_mix.png" title="slide_o_mix's avatar" /> slide_o_mix:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-20355?focusedId=217387&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-217387">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Yes, please open a new issue and provide more information.</p>
</pre>
</details>

</ul>
</details>

<p>Yes, please open a new issue and provide more information.</p>

**Comment by jenkins-infra-bot** [comment]
<i>[Original `relates_to` from Jira: <a class="jira-relationship" href="https://issue-redirect.jenkins.io/issue/16990">JENKINS-16990</a>]</i>
