### ISSUE TITLE
[JENKINS-18728] FATAL exception in hudson.model.AbstractBuild.getPreviousBuild at the end of matrix parent job

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/email-ext-plugin#924]
<p>After upgrading from 2.25 to 2.30.2 on Jenkins 1.480.3, every matrix project throws the following exception at the end of the matrix parent job.</p>

<p>I have the "Trigger only for parent job" option enabled.</p>

<p>FATAL: hudson.model.AbstractBuild.getPreviousBuild()Lhudson/model/AbstractBuild;<br/>
java.lang.NoSuchMethodError: hudson.model.AbstractBuild.getPreviousBuild()Lhudson/model/AbstractBuild;<br/>
	at hudson.plugins.emailext.plugins.trigger.FixedTrigger.trigger(FixedTrigger.java:21)<br/>
	at hudson.plugins.emailext.ExtendedEmailPublisher._perform(ExtendedEmailPublisher.java:282)<br/>
	at hudson.plugins.emailext.ExtendedEmailPublisher.access$100(ExtendedEmailPublisher.java:82)<br/>
	at hudson.plugins.emailext.ExtendedEmailPublisher$1.endBuild(ExtendedEmailPublisher.java:800)<br/>
	at hudson.matrix.MatrixBuild$MatrixBuildExecution.post2(MatrixBuild.java:387)<br/>
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:640)<br/>
	at hudson.model.Run.execute(Run.java:1527)<br/>
	at hudson.matrix.MatrixBuild.run(MatrixBuild.java:289)<br/>
	at hudson.model.ResourceController.execute(ResourceController.java:88)<br/>
	at hudson.model.Executor.run(Executor.java:237)<br/>
	at hudson.model.OneOffExecutor.run(OneOffExecutor.java:66)</p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=masariello">masariello</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-18728" target="_blank">FATAL exception in hudson.model.AbstractBuild.getPreviousBuild at the end of matrix parent job</a></i></summary>
<i><ul>
<li><b>assignee</b>: <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/slide_o_mix.png" title="slide_o_mix's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=slide_o_mix">slide_o_mix</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Blocker
<li><b>component(s)</b>: email-ext-plugin
<li><b>resolution</b>: Not A Defect
<li><b>resolved</b>: 2013-07-12T13:34:39+00:00
<li><b>votes</b>: 0
<li><b>watchers</b>: 2
<li><b>imported</b>: 20251211-172001
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>After upgrading from 2.25 to 2.30.2 on Jenkins 1.480.3, every matrix project throws the following exception at the end of the matrix parent job.</p>

<p>I have the "Trigger only for parent job" option enabled.</p>

<p>FATAL: hudson.model.AbstractBuild.getPreviousBuild()Lhudson/model/AbstractBuild;
java.lang.NoSuchMethodError: hudson.model.AbstractBuild.getPreviousBuild()Lhudson/model/AbstractBuild;
	at hudson.plugins.emailext.plugins.trigger.FixedTrigger.trigger(FixedTrigger.java:21)
	at hudson.plugins.emailext.ExtendedEmailPublisher._perform(ExtendedEmailPublisher.java:282)
	at hudson.plugins.emailext.ExtendedEmailPublisher.access$100(ExtendedEmailPublisher.java:82)
	at hudson.plugins.emailext.ExtendedEmailPublisher$1.endBuild(ExtendedEmailPublisher.java:800)
	at hudson.matrix.MatrixBuild$MatrixBuildExecution.post2(MatrixBuild.java:387)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:640)
	at hudson.model.Run.execute(Run.java:1527)
	at hudson.matrix.MatrixBuild.run(MatrixBuild.java:289)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:237)
	at hudson.model.OneOffExecutor.run(OneOffExecutor.java:66)</p></pre>
</details>
</details>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>masariello:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-18728?focusedId=181524&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-181524">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>I just realized the latest versions of the plug-in are meant for Jenkins 1.509 or newer</p>
</pre>
</details>

</ul>
</details>

<p>I just realized the latest versions of the plug-in are meant for Jenkins 1.509 or newer</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/slide_o_mix.png" title="slide_o_mix's avatar" /> slide_o_mix:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-18728?focusedId=181527&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-181527">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>That's correct, sorry if there was any confusion.</p>
</pre>
</details>

</ul>
</details>

<p>That's correct, sorry if there was any confusion.</p>
